----
kind: pipeline
name: Build
type: docker

steps:
  - name: "Quality Control"
    image: node:12.14-alpine
    commands:
      - apk add git
      - yarn install
      - yarn lint
      - yarn test:unit

  - name: "Build docker image"
    image: "plugins/docker"
    settings:
      auto_tag: true
      repo: "${DRONE_REPO_NAMESPACE}/${DRONE_REPO_NAME}"
      username: { from_secret: "docker_hub_username" }
      password: { from_secret: "docker_hub_password" }
    when:
      ref: { include: [ "refs/tags/20??.*.*", "refs/heads/master" ] }
      event: [ "tag" ]
