----
kind: pipeline
name: Build
type: docker

steps:
  - name: "Quality Control"
    image: node:12.14-alpine
    environment:
      C_PKG: ${C_FLAVOUR}-server-corredor
    commands:
      - apk add git
      - yarn install --non-interactive --no-progress --emoji false
      - yarn lint
      - yarn test:unit


  - name: "Build"
    image: node:12.14-alpine
    environment:
      C_PKG: ${C_FLAVOUR}-server-corredor
    commands:
    - mkdir "${C_PKG}"
    - yarn global add modclean
    - yarn install --production --non-interactive --no-progress --emoji false
    - modclean --run --no-progress --error-halt
    - yarn build
    - mv dist node_modules "${C_PKG}"
    - tar -czf "${C_PKG}-${DRONE_TAG}.tar.gz" ${C_PKG}
    when:
      event: [ tag ]
      ref:
      - refs/tags/20??.3.*
      - refs/tags/20??.6.*
      - refs/tags/20??.9.*
      - refs/tags/20??.12.*


