----
kind: pipeline
name: Build
type: docker

steps:
  - name: "Build production release image"
    image: "plugins/docker"
    settings:
      auto_tag: true
      repo: "${DRONE_REPO_NAMESPACE}/${DRONE_REPO_NAME}"
      username: { from_secret: "docker_hub_username" }
      password: { from_secret: "docker_hub_password" }
    when:
      ref: { include: [ "refs/tags/20??.*.*", "refs/heads/master", "refs/heads/preview" ] }
      event: [ "push", "tag" ]
