----
kind: pipeline
name: Build
type: docker

steps:
  - name: "Quality Control"
    image: node:12.14-alpine
    commands:
      - apk add git
      - yarn install --non-interactive --no-progress --emoji false
      - yarn lint
      - yarn test:unit


  - name: "Build"
    image: node:12.14-alpine
    commands:
    - apk add git
    - yarn global add modclean
    - yarn install --production --non-interactive --no-progress --emoji false
    # doing node modules cleanup
    # since we can not run std. build
    - modclean --run --no-progress --error-halt
    - yarn build
    - mkdir corteza-server-corredor
    - mv dist node_modules corteza-server-corredor
    - tar -czf "corteza-server-corredor-${DRONE_TAG}.tar.gz" corteza-server-corredor
    - du -h "corteza-server-corredor-${DRONE_TAG}.tar.gz"
    when:
      event: [ tag ]
      ref:
      - refs/tags/20??.3.*
      - refs/tags/20??.6.*
      - refs/tags/20??.9.*
      - refs/tags/20??.12.*
