kind: pipeline
name: Build & Pack

steps:
  - name: build image
    image: plugins/docker
    settings:
      repo: ${DRONE_REPO_NAMESPACE}/${DRONE_REPO_NAME}
      auto_tag: true # generate tag names automatically based on git branch and git tag
      username:
        from_secret: docker_hub_username
      password:
        from_secret: docker_hub_password
    when:
      ref:
        - refs/heads/master
        - refs/heads/beta
        - refs/heads/feature-*
        - refs/tags/20??.*.*
      events: [ tag, push ]

trigger:
